### ISSUE TITLE
NameError: global name 'matrix_' is not defined

### ISSUE THREAD

**Issue by bibrgr** [csbio/BEAN-counter#4]
Running the pipeline with the sample data provided and ran into this error during step 2 of process_screen.py. Not too familiar with python but it seems the matrix_ variable is declared in line 212 of normalizeUsingAllControlsAndSave & not sure if it is declared globally.

Traceback (most recent call last):
  File "..\master_scripts\process_screen.py", line 167, in <module>
    main(args.config_file, args.start, args.stop)
  File "..\master_scripts\process_screen.py", line 117, in main
    counts_to_zscores.main(config_file, lane_id)
  File "C:\path\to\BEAN-counter-2.6.1\scripts\counts_to_zscores.py", line 671, in main
    normalized_dataset, mean_control_profile = normalizeUsingAllControlsAndSave(config_params, batch_outfolder, filtered_dataset, control_condition_ids, lane_id)
  File "C:\path\to\BEAN-counter-2.6.1\scripts\counts_to_zscores.py", line 219, in normalizeUsingAllControlsAndSave
    matrix = np.vstack(pool.map(normalize_one_profile, range(matrix.shape[1]))).T
  File "C:\Python27\lib\multiprocessing\pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
NameError: global name 'matrix_' is not defined

**Comment by RussianImperialScott** [comment]
Hmmmmm thanks for raising this! The soonest I can look at this is over the weekend. Feel free to fork and test on a new branch, and submit a PR if you get it to work.
